import React from 'react';

function Bus(props) {
    return (
        <div>
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            This is a Bus Page......
            
        </div>
    );
}

export default Bus;